name: Hello Agile
on:
  push:
    branches: [ dev ]   # Runs only when pushing to dev
  pull_request:
    branches: [ main ]  # Runs when PR targets main
jobs:
say_hello:
 runs-on: ubuntu-latest
 steps:
 - name: Print Hello
 run: echo "Hello from GitHub Actions!"
